export const STOCKS = [
  { symbol: "SPOT", name: "Spotify" },
  { symbol: "NKE", name: "Nike" },
  { symbol: "BBY", name: "Best Buy" },
  { symbol: "AMC", name: "AMC Entertainment" },
  { symbol: "TGT", name: "Target" },
  { symbol: 'AAPL', name: 'Apple' },
  { symbol: 'MSFT', name: 'Microsoft' },
  { symbol: 'GOOGL', name: 'Alphabet' },
  { symbol: 'AMZN', name: 'Amazon' },
  { symbol: "NVDA", name: "NVIDIA" },
  { symbol: "META", name: "Meta" },
  { symbol: "TSLA", name: "Tesla" },
  { symbol: "AMD", name: "AMD" },
  { symbol: "NFLX", name: "Netflix" },
  { symbol: "JPM", name: "JPMorgan Chase" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "KO", name: "Coca-Cola" },
  { symbol: "DIS", name: "Disney" },
  { symbol: "ORCL", name: "Oracle" },
  { symbol: "INTC", name: "Intel" },
  { symbol: "CSCO", name: "Cisco" },
  { symbol: "ADBE", name: "Adobe" },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "CRM", name: "Salesforce" },
  { symbol: "UBER", name: "Uber" },
  { symbol: "LYFT", name: "Lyft" },
  { symbol: "SQ", name: "Block (Square)" },
  { symbol: "SHOP", name: "Shopify" },
  { symbol: "BABA", name: "Alibaba" },
  { symbol: "BA", name: "Boeing" },
];